version: "3.9"

services:
  db:
    image: postgres:15
    container_name: resume-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: resumes
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  api:
    build:
      context: ./Resume Builder   # your Dockerfile location
      dockerfile: Dockerfile
    container_name: resumebackend-api
    env_file:
      - .env
    environment:
      - ENV=production
      - TEX_BIN=xelatex
      - DATABASE_URL=postgresql+asyncpg://postgres:1234@db:5432/resumes
    volumes:
      - ./Resume Builder:/app      # mount the full project (includes alembic)
      - uploads:/app/build
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    networks:
      - backend

  nginx:
    image: nginx:stable
    container_name: resumebackend-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
      - uploads:/app/build
    depends_on:
      - api
    networks:
      - backend

volumes:
  uploads:
  pgdata:

networks:
  backend:
    driver: bridge
